# Generated by Django 4.2.5 on 2023-11-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargoId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cargoNombre', models.CharField(max_length=35)),
                ('minSalario', models.IntegerField()),
                ('maxSalario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departId', models.IntegerField(primary_key=True, serialize=False)),
                ('departNombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellidoPaterno', models.CharField(max_length=60)),
                ('apellidoMaterno', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('fechaContratacion', models.DateField()),
                ('fechaNacimiento', models.DateField()),
                ('salario', models.IntegerField()),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cargoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rrhh.cargo')),
                ('departamentoId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rrhh.departamento')),
            ],
        ),
    ]
